use_frameworks!

platform :ios, '10.0'

target 'XDTools_Example' do
  pod 'XDTools', :path => '../'

  target 'XDTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end




